---
- name: Provision all servers
  hosts: all
  become: yes
  roles:
    - post-install 

- name: Provision web servers
  hosts: webservers
  become: yes
  roles:
    - webserver

- name: Provision DB servers
  hosts: dbservers
  become: yes
  roles:
    - database